version: 1
devices:
    require_known_device: true
    paired_devices:
        ipad-rob:
            secret_hash: ""
        iphone-rob:
            secret_hash: ""
        test-phone:
            secret_hash: 2a3eeea0d7ca22c2dec670362fd6933471aaea18eebaf949e399d3d57de67f07
security:
    require_arming: true
    enforce_allowlist: true
